### PR TITLE
Feature/navbar

### PR DESCRIPTION
**Pull request by jenovs**

### CODE REVIEW

**Comment by nikrb** [comment]
@jenovs great job Viktor.
Just a small point, looks like prop-types is missing from dependencies.
Are there any opportunities to add a test or two?

**Comment by jenovs** [comment]
Added `prop-types` to dependencies and couple tests.

**Comment by nikrb** [comment]
@jenovs hey viktor, sorry to be a pain, it looks great, but when I run npm install I get the following:
```
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
```
Shouldn't these be in package.json or is this expected? Do I just install them locally?
When I run npm test:
`Error: Cannot find module '/home/nik/projects/voyage4/bears-25/frontend/node_modules/jest-cli'`
Is this missing or should I have it installed globally perhaps?

**Comment by jenovs** [comment]
Regarding the first one: https://github.com/webpack-contrib/schema-utils/issues/23 (looks like something we can ignore for now).
~~Regarding the second one: Incorrect version in `package.json` (should be `v5`: https://github.com/jenovs/cra-with-lintin/blob/master/package.json#L20)~~
I stand corrected. They updated dependencies. Looking into.
Deleted `node_modules` and lock file and reinstalled without warnings :thinking:   

all-good

Also I don't install anything globally (except node and npm).

**Pull request merged**
