### PR TITLE
Feature/user edit

### PR DESCRIPTION
**Pull request by jenovs**
Fefactor UserPage component using Material-UI

### CODE REVIEW

**Comment by nikrb** [comment]
I don't think we need a visitor role. Visitor's aren't registered?

**Comment by nikrb** [comment]
there's a big blank area at the top of the profile details.
profileblankarea

**Comment by jenovs** [comment]
I put roles in separate file so they can be easy added/edited/removed. Feel free to modify them as you see fit.
The big blank space is for avatar. Added fallback to placeholder.
Also I used fields from mock data, so when we'll know final shape of the user schema the fields should be modified accordingly.

**Review by nikrb — APPROVED** [review]
loving the material-ui

**Pull request merged**
