### PR TITLE
Feat/content moderation

### PR DESCRIPTION
**Pull request by nikrb**

### CODE REVIEW

**Comment by jenovs** [comment]
Why sudden switch to `snake_case` instead of `camelCase`?

**Review by jenovs — CHANGES_REQUESTED** [review]
If `admin` edits an article, the article gets updated, but stays locked for further edits and it doesn't show up in `requests`.

I get `User routes` tests failing with `unauthorized`.

**Comment by nikrb** [comment]
thanx for spotting the admin update failure will look into it

I've used snake case from the start for db fields?
I the past I have favoured for local vars and camelcase for properties ... but it seems I'm out of vogue. So trying to use camelcase everywhere - just too late for db.

I thought I had run the tests and as we skip auth for tests surprised there's an auth failure. will look into it.

**Comment by nikrb** [comment]
not seeing the user routes error:
```
  User model
    insert
      ✓ should insert a new user (146ms)
      ✓ should register a new user (1240ms)
      ✓ should reject duplicate username on registration (1118ms)

  User routes
    ✓ gets all users (147ms)

  User routes
    ✓ gets user detail

Closed database connection

  5 passing (3s)
```

**Comment by jenovs** [comment]
I guess you have something in your `.env.test` file that makes tests pass.

```js
image upload directory present
Connected to database
server started PORT: 3001
  User model
    insert
      ✓ should insert a new user
      ✓ should register a new user (333ms)
      ✓ should reject duplicate username on registration (328ms)

  User routes
GET /api/v1/users 401 12 - 10.395 ms
    1) gets all users

  User routes
GET /api/v1/user/5b2fe0b80267806030526936 401 12 - 1.322 ms
    2) gets user detail

Closed database connection

  3 passing (807ms)
  2 failing

  1) User routes
       gets all users:
     Uncaught Error: Unauthorized
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:626:17)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:795:18)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) User routes
       gets user detail:
     Uncaught Error: Unauthorized
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:626:17)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:795:18)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by nikrb** [comment]
not that old chestnut :)
*should* be the same as sample.env
```
PORT=3001
NODE_ENV=test
MONGO_URI=mongodb://localhost:27017/cms_test
GITHUB_CLIENT_ID=xxx
GITHUB_CLIENT_SECRET=XXX
APP_URL=http://127.0.0.1:3001
IMAGE_UPLOAD_DIR=./uploads
```

**Comment by nikrb** [comment]
added tests for BE article upsert.
Had some issue with findAndUpdate being delayed and not updating properly when resetting the edit_lock. Reworked code.

**Comment by jenovs** [comment]
Chestnut cracked.
`.env.sample` has `NODE_ENV=development` :man_facepalming: 
I think `.env.test` could be un-gitignored and added to version control. Also because is one just copies `.env.sample` to `.env.test` the local database will be wiped after every test run :grinning:

**Review by jenovs — APPROVED** [review]

**Comment by nikrb** [comment]
you have a good point there - I actually have my github api keys in there, but they aren't required.

**Pull request merged**
