### PR TITLE
Feature/search results

### LINKED ISSUE #10: As a visitor I want to be able to search the content so I can find things quickly

### PR DESCRIPTION
**Pull request by jenovs**
Display search results in CMSContainer.
Added dependency. Don't forget to `npm i` :grinning: 
Closes #10

### CODE REVIEW

**Comment by nikrb** [comment]
looks good.
Only just noticed the extra margin on the left in mobile - because of the hamburger for the cms tree? Would it be a lot of work to fix?

**Review by nikrb — APPROVED** [review]

**Comment by jenovs** [comment]
Fix added.
Also added a button to close search results (quick fix, so it's ugly :blush: ).

**Comment by nikrb** [comment]
sorry to harp on about the mobile left margin, but it's sticking out like a sore thumb now when looking at articles on mobile. Removing the button (for search results) looks a bit odd.
I appreciate it may be too much re-design at this point, I'll add it to issues for the future if you think it's gonna be a pain.
:heart: the close button :grinning:

**Comment by jenovs** [comment]
The gap was always there :grinning: 
Let's treat getting rid of it as a separate fix (that will also remove removing of button for search results)

**Pull request merged**
