### PR TITLE
Feature/content area

### PR DESCRIPTION
**Pull request by keith1111**
notes.
1) ContentArea element in main page is only for test and will be replaced with ContentViewPage (when we merge content-area and sidebar branches into develop)
2) ContentArea element can get props (path to JSON file), read JSON file from that path and display it in HTML elements (engine is in JSONHandle directory).
3) There is a big field to improve, but for now the component matches basic existing needs.
4) JSON file with data is placed in 'public'  dir not it 'src', i see no way to aviod that because it builds to 'public' and this is the only way to see the working instance.

### CODE REVIEW

**Comment by nikrb** [comment]
sorry @keith1111  but there are lots of linting errors that need to be fixed. Run `npm run lint` in the frontend directory.
I appreciate the work you have put in with the mock data, but it doesn't need to be so complex. If you have a look at viktors `Articles` component his approach is quite sufficient and best practice I suspect ;)   I'd appreciate @jenovs opinion, but I think it's ok to leave it as it is for now, just bear it in mind for the future.

**Review by nikrb — CHANGES_REQUESTED** [review]
linting errors need fixing

**Comment by keith1111** [comment]
errors fixed, did not touch 1 file HTMLToJSON.js which will be modified later, so now is no reason useless to prettier for that file.

**Review by jenovs — CHANGES_REQUESTED** [review]
`create-react-app` doesn't have to be in project-dependencies. You should remove `package.json` and `package-lock.json` from your commit.

**Comment by keith1111** [comment]
deleted unwanted files

**Comment by nikrb** [comment]
yikes! @keith1111 you have removed package.json. I think you misunderstood @jenovs ... he meant just remove your updates to the package files.
I will have a look and fix things and then we can go from there.
Again, apologies for not seeing the update. In future just shout in slack after a day if nothing seems to be happening :)

**Comment by nikrb** [comment]
@jenovs can you review my last changes here and I'll merge to develop thanx

**Review by jenovs — APPROVED** [review]

**Comment by jenovs** [comment]
Wait, isn't that `package.json` very old???
My `package.json` is 38 lines.

**Review by nikrb — APPROVED** [review]

**Pull request merged**
