### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by nikrb**
fleshed out landing page, removed old comments and added a test

### CODE REVIEW

**Comment by jenovs** [comment]
1. Empty `div` could be replaced with `React.Fragment` (https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html).
2. Inconsistency in the ordering of CSS properties make my OCD go haywire :grin: 
3. Tests are failing (I see `jest-styled-components` in `package.json`, but not in the test file).

**Comment by nikrb** [comment]
hey viktor, thanx for the feedback. Do you really have OCD or just messing with me? :)

1. empty div? Do you mean the unstyled div? I didn't realise that was bad, but I'll replace it.
2. Inconsistent ordering? ah, `Content` in styled.js wants to come after `Article`?
3. test: yes darn it ... loving snapshots - not! ;)

I haven't used jest-styled-components due to the hard-coded nature of the page. I just added the package ready for when needed.

**Comment by jenovs** [comment]
No OCD yet, just a strong preference for order :grin: 
1. I mean unnecessary node whose only role is to wrap everything else. React 16 introduced fragments to get rid of those.
2. No, there are cases when functions must be in particular order. I'm talking about properties, like `align-items`, `color` etc. I personally prefer alphabetical order, because it's the least ambiguous.

**Comment by nikrb** [comment]
good! I think alphabetical is good idea.
1. so this is fixed now, or is there something else?
2. oh right ok yes, just lazyness, I'll reorder props.

**Review by jenovs — APPROVED** [review]
Looks good to me

**Review by keith1111 — APPROVED** [review]
all good

**Review by giovannisampaio — APPROVED** [review]
good!

**Pull request merged**
