### PR TITLE
Feature/content area

### PR DESCRIPTION
**Pull request by keith1111**
Section where main content of page will load. Now shows only the example data, in future i'll try to figure out how to get needed HTML data from our target chingu wiki

### CODE REVIEW

**Comment by nikrb** [comment]
I would try just copying the wiki text and paste it into a json file which you can then import. Ultimately the import will change to an action which does a fetch request to our backend. My two penneth anyway :)

**Comment by keith1111** [comment]
Backend will grab data from chingu wiki, and frontend will grab data from backend? Now we need a temporary json file to make simulation of that process , right i understand?

**Comment by nikrb** [comment]
interesting idea, though I imagined we would keep the data in our database. *If* chingu do adopt it, the wiki won't be used anymore, hence we will keep the data in our db.
Yes re temporary json file.

**Comment by nikrb** [comment]
@keith1111 I have pulled the branch and had a look. I notice a few things that I would rather be done before we merge to develop. As always I'm open to discussion :) 
1. the content area component should not be inside the landing page component. Just replace the landing page in top level app.js for now.
2. I would prefer to see some of the wiki text with titles for the merge (the lorem ipsum suggestion was just for you whilst developing)
3. I'm seeing a lot of linter errors. Are you having trouble linting? (try running npm lint)

**Comment by keith1111** [comment]
1) 50% understood, i thought content area is a part of landing page. i am going to rewrite, but i dont understand where will be the component called from in that case? when we have no landing page? 
2) what are 'titles for the merge' like ? maybe some example ?
3) never tried: can not be sure and talk about troubles, i suppose 'Linting' is a program to find potential errors in code? will try it and then we see the result

**Comment by nikrb** [comment]
1. The landing page is what people see when they first visit the site. It contains features etc of the site. It has the navbar above it and the footer below. Content view page is accessed from the cms menu (my bad, this isn't on the wireframes so totally understand your confusion, apologies). It has the navbar above it, footer below and sidebar to the left.
2. some examples: `feature/content-area`, `fix/some-bug`, `style/navbar-colour`
3. a linter ensures we all write code the same way, or rather so all the code is formatted the same. You may be able to see linter errors in your editor (I use atom and it works great). You should always run test `npm test` and linting `npm run lint` and fix any failures before creating a pr.

Hope that helps, always happy to answer questions and discuss :)

**Pull request closed without merging**
